openapi: 3.0.1
info:
  title: test-api
  version: 1.0.0
servers:
  - url: http://{host}:{port}/api/v0
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '7001'
paths:
  "/users":
    $ref: "./paths/users.yaml"
  "/users/{userId}":
    $ref: "./paths/users.userId.yaml"

components:
  schemas:
    $ref: '#/components/schemas/index.yaml'

x-google-backend:
  address: https://_API_HOST
  protocol: h2
  deadline: 60.0
x-original-swagger-version: "2.0"
