swagger: '2.0'
info:
  title: test-api
  version: 1.0.0
host: _ENDPOINTS_HOST
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
x-google-backend:
  address: https://_API_HOST
  protocol: h2
  deadline: 60.0
paths:
  /users:
    get:
      summary: ユーザー一覧
      operationId: getUsers
      responses:
        '200':
          description: ユーザー一覧
          schema:
            $ref: '#/definitions/GetUsersResponse'
definitions:
  GetUsersResponse:
    $ref: './definitions/GetUsersResponse.yaml'
  User:
    $ref: './definitions/User.yaml'