/*
 * test-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */
package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetUsers - ユーザー一覧
func GetUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}